### ISSUE TITLE
[US]: Modifié les informations d'un compte

### ISSUE THREAD

**Issue by ghost** [IUT-Blagnac/sae3-01-devapp-g2b-11#26]
### User Story

En tant qu'utilisateur connectée, je souhaite modifier les informations de mon compte

### Importance

Should

### Critères d'acceptation

- [x] #17 
- [x] #33 
- [x] #41 

### Détails

Quand l'utilisateur est connecter, dans la page de connexion est afficher un bouton qui au clique de celui-ci redirige vers un formulaire permettant de modifié les informations du compte.

### Tâches associées

- [X] Écrire un test
- [X] Coder
- [x] Écrire la doc

**Comment by Chris-973** [comment]
Amélioration de l'US
